### ISSUE TITLE
Add comment that get_coefficients requires a tuple of arrays as output to the docs

### ISSUE THREAD

**Issue by pmaxted** [dfm/celerite2#2]
Here is a minimal code block to reproduce the error 

    from celerite2.terms import Term
    class CosineTerm(Term):
        def __init__(self, omega_j, sigma_j):
            self.omega_j = omega_j
            self.sigma_j = sigma_j
        def get_coefficients(self):
            return 0, 0, self.sigma_j, 0, 0, self.omega_j
    kernel =  CosineTerm(1,0.1) + CosineTerm(2,0.2)
    kernel.get_coefficients()

The following error is thrown at line 161 of terms.py

    ValueError: zero-dimensional arrays cannot be concatenated

**Comment by dfm** [comment]
Hi Pierre, I think that the following is what you want (disclaimer: typed on GitHub):

```python
    def get_coefficients(self):
        empty = np.empty(0)
        zero = np.zeros(1)
        return empty, empty, np.array([self.sigma_j]), zero, zero, np.array([self.omega_j])
```

**Comment by pmaxted** [comment]
This fixes the issue, thanks.

**Comment by pmaxted** [comment]
Perhaps this should be noted/explained  in the documentation - https://celerite2.readthedocs.io/en/latest/api/python/#celerite2.terms.Term.get_coefficients

**Comment by dfm** [comment]
Sure! I'm also planning on making a tutorial about custom kernels, but I'm not there yet. Let's keep this open to remember.

**Comment by dfm** [comment]
Done: https://celerite2.readthedocs.io/en/latest/api/python/#celerite2.terms.Term.get_coefficients
